<?php
// Installer for the CMS

// Prevent access if the config file already exists, which implies installation is complete.
if (file_exists(__DIR__ . '/../config/database.php')) {
    // A more user-friendly message could be used.
    // die("Installer has already been run. Please delete the /install directory for security.");
}

// Basic error reporting for installation
error_reporting(E_ALL);
ini_set('display_errors', 1);

if (session_status() === PHP_SESSION_NONE) {
    session_start();
}

$step = (int)($_GET['step'] ?? 1);

// --- Step 1: Language Selection Logic ---
if ($step === 1 && isset($_POST['submit_lang'])) {
    $_SESSION['install_lang'] = $_POST['language'] === 'ro' ? 'ro' : 'en';
    header('Location: index.php?step=2');
    exit();
}

$error = null;
// --- Step 2: DB Config Logic ---
if ($step === 2 && isset($_POST['submit_db'])) {
    $db_host = $_POST['db_host'];
    $db_name = $_POST['db_name'];
    $db_user = $_POST['db_user'];
    $db_pass = $_POST['db_pass'];
    $db_prefix = preg_replace('/[^a-zA-Z0-9_]/', '', $_POST['db_prefix']); // Sanitize prefix

    // Attempt connection
    $conn = @new mysqli($db_host, $db_user, $db_pass, $db_name);
    if ($conn->connect_error) {
        $error = "Database connection failed: " . $conn->connect_error;
    } else {
        // Connection successful, generate config file
        $config_content = "<?php
// Generated by the installer
define('DB_HOST', '" . addslashes($db_host) . "');
define('DB_USER', '" . addslashes($db_user) . "');
define('DB_PASS', '" . addslashes($db_pass) . "');
define('DB_NAME', '" . addslashes($db_name) . "');
define('DB_PREFIX', '" . addslashes($db_prefix) . "');

// The rest of your database connection logic can go here...
// For simplicity, we'll just define constants.
?>";
        // Attempt to write the config file
        if (@file_put_contents(__DIR__ . '/../config/db_config_temp.php', $config_content)) {
             $_SESSION['install_db'] = [
                'host' => $db_host,
                'name' => $db_name,
                'user' => $db_user,
                'pass' => $db_pass,
                'prefix' => $db_prefix
            ];
            $_SESSION['install_site_name'] = $_POST['site_name'];
            header('Location: index.php?step=3');
            exit();
        } else {
            $error = "Could not write to config file. Please check file permissions on the /config directory.";
        }
        $conn->close();
    }
}


// --- Step 3: Admin Creation Logic ---
if ($step === 3 && isset($_POST['submit_owner'])) {
    if (empty($_SESSION['install_db'])) {
        $error = "Database configuration is missing. Please start over.";
        $step = 2; // Send back to step 2
    } else {
        $db = $_SESSION['install_db'];
        $conn = @new mysqli($db['host'], $db['user'], $db['pass'], $db['name']);

        if ($conn->connect_error) {
            $error = "Could not connect to the database with the stored credentials.";
            $step = 2;
        } else {
            // --- 1. Read and modify the schema ---
            $schema_sql = file_get_contents(__DIR__ . '/../config/schema.sql');
            $prefix = $db['prefix'];

            // Replace table names and foreign key references
            $tables = ['users', 'roles', 'permissions', 'user_roles', 'role_permissions', 'settings', 'menus', 'menu_permissions', 'plugins'];
            foreach ($tables as $table) {
                $schema_sql = str_replace("`$table`", "`{$prefix}{$table}`", $schema_sql);
            }

            // --- 2. Execute the schema query ---
            if (!$conn->multi_query($schema_sql)) {
                $error = "Error creating database tables: " . $conn->error;
            } else {
                // Clear multi_query results
                while ($conn->next_result()) { $conn->store_result(); }

                // --- 3. Create the Owner user ---
                $owner_user = trim($_POST['username']);
                $owner_email = trim($_POST['email']);
                $owner_pass = password_hash($_POST['password'], PASSWORD_DEFAULT);

                $stmt = $conn->prepare("INSERT INTO `{$prefix}users` (username, email, password) VALUES (?, ?, ?)");
                $stmt->bind_param("sss", $owner_user, $owner_email, $owner_pass);
                $stmt->execute();
                $owner_id = $conn->insert_id;

                // --- 4. Create Owner role and assign it ---
                // The schema already adds 'Admin' and 'User', let's add 'Owner'
                $conn->query("INSERT INTO `{$prefix}roles` (id, role_name, description) VALUES (1, 'Owner', 'Site owner with all permissions.') ON DUPLICATE KEY UPDATE role_name=VALUES(role_name)");
                $conn->query("INSERT INTO `{$prefix}user_roles` (user_id, role_id) VALUES ($owner_id, 1)");
                $conn->query("INSERT INTO `{$prefix}user_roles` (user_id, role_id) VALUES ($owner_id, 2)"); // Also make them an Admin

                // --- 5. Update site name setting ---
                $site_name = $_SESSION['install_site_name'];
                $conn->query("UPDATE `{$prefix}settings` SET setting_value = '" . $conn->real_escape_string($site_name) . "' WHERE setting_key = 'site_name'");

                // --- 6. Finalize: rename the temp config file ---
                rename(__DIR__ . '/../config/db_config_temp.php', __DIR__ . '/../config/database.php');

                // --- 7. Create lock file ---
                file_put_contents(__DIR__ . '/install.lock', 'Installation completed on ' . date('Y-m-d H:i:s'));

                session_destroy();
                header('Location: index.php?step=4');
                exit();
            }
        }
    }
}


// --- HTML Output ---
?>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>CMS Installer</title>
    <style>
        body { font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, "Helvetica Neue", Arial, sans-serif; background-color: #f0f2f5; display: flex; justify-content: center; align-items: center; min-height: 100vh; margin: 0; }
        .installer-container { background-color: #fff; padding: 2.5rem; border-radius: 8px; box-shadow: 0 4px 12px rgba(0,0,0,0.1); width: 100%; max-width: 550px; }
        h1 { text-align: center; color: #333; margin-top: 0; padding-bottom: 1rem; border-bottom: 1px solid #eee; }
        .form-group { margin-bottom: 1.25rem; }
        label { display: block; margin-bottom: 0.5rem; font-weight: 600; color: #555; }
        select, input[type=text], input[type=password] { width: 100%; padding: 10px; border-radius: 4px; border: 1px solid #ccc; box-sizing: border-box; transition: border-color 0.2s; }
        input:focus { border-color: #007bff; outline: none; }
        .btn { display: block; width: 100%; padding: 12px; background-color: #007bff; color: #fff; border: none; border-radius: 4px; font-size: 1rem; cursor: pointer; transition: background-color 0.2s; }
        .btn:hover { background-color: #0056b3; }
        .error { border: 1px solid #dc3545; background-color: #f8d7da; color: #721c24; padding: 1rem; margin-bottom: 1rem; border-radius: 4px; }
        .success { border: 1px solid #28a745; background-color: #d4edda; color: #155724; padding: 1rem; margin-bottom: 1rem; border-radius: 4px; }
    </style>
</head>
<body>
    <div class="installer-container">
        <h1>CMS Installer</h1>

        <?php if ($step === 1): ?>
            <h2>Step 1: Select Language</h2>
            <form action="index.php?step=1" method="POST">
                <div class="form-group">
                    <label for="language">Language / Limbă</label>
                    <select name="language" id="language" class="form-control">
                        <option value="en">English</option>
                        <option value="ro">Română</option>
                    </select>
                </div>
                <button type="submit" name="submit_lang" class="btn">Next Step &rarr;</button>
            </form>
        <?php elseif ($step === 2): ?>
            <h2>Step 2: Database & Site Configuration</h2>
            <?php if ($error): ?>
                <div class="error"><?php echo $error; ?></div>
            <?php endif; ?>
            <form action="index.php?step=2" method="POST">
                <div class="form-group">
                    <label for="db_host">Database Host</label>
                    <input type="text" name="db_host" id="db_host" value="127.0.0.1" required>
                </div>
                <div class="form-group">
                    <label for="db_name">Database Name</label>
                    <input type="text" name="db_name" id="db_name" required>
                </div>
                <div class="form-group">
                    <label for="db_user">Database User</label>
                    <input type="text" name="db_user" id="db_user" required>
                </div>
                <div class="form-group">
                    <label for="db_pass">Database Password</label>
                    <input type="password" name="db_pass" id="db_pass">
                </div>
                 <div class="form-group">
                    <label for="db_prefix">Table Prefix</label>
                    <input type="text" name="db_prefix" id="db_prefix" value="cms_">
                </div>
                <hr style="margin: 2rem 0;">
                <div class="form-group">
                    <label for="site_name">Site Name</label>
                    <input type="text" name="site_name" id="site_name" value="My Awesome Site" required>
                </div>
                <button type="submit" name="submit_db" class="btn">Test Connection & Proceed</button>
            </form>
        <?php elseif ($step === 3): ?>
            <h2>Step 3: Create Owner Account</h2>
            <p>This will be the main administrator account with full permissions.</p>
            <form action="index.php?step=3" method="POST">
                <div class="form-group">
                    <label for="username">Username</label>
                    <input type="text" name="username" id="username" required>
                </div>
                <div class="form-group">
                    <label for="email">Email Address</label>
                    <input type="text" name="email" id="email" required>
                </div>
                <div class="form-group">
                    <label for="password">Password</label>
                    <input type="password" name="password" id="password" required>
                </div>
                <button type="submit" name="submit_owner" class="btn">Finish Installation</button>
            </form>
        <?php elseif ($step === 4): ?>
             <h2>Installation Complete!</h2>
             <div class="success">
                Congratulations! The CMS has been installed successfully.
             </div>
             <p><strong>For security, please delete the entire `/install` directory from your server immediately.</strong></p>
             <a href="/index.php" class="btn">Go to Homepage</a>
        <?php endif; ?>

    </div>
</body>
</html>
